### ISSUE TITLE
Gulp not watching .pug inside sub directories

### ISSUE THREAD

**Issue by karneaud** [revengecreative/pug-sass-starter-kit#3]
I currently have pug files in a sub directory of the views folder...but gulp doesn't seem to run when these files are updated/ modified. I would need to edit the main index.pug in order to preview modified changes from the sub directory pug file.

I'm on Windows 8.1 running the latest homestead/ vagrant with yarn 1.2.3

**Comment by davidepalazzo** [comment]
You'll need to restart your task if you add a new subfolder. Gulp's built-in watcher is quiet basic and doesn't pick up on new folders or files. You can add that functionality using something like [gulp-watch](https://www.npmjs.com/package/gulp-watch).
